### ISSUE TITLE
Send ai statistics to Slack: registered frozen

### ISSUE THREAD

**Issue by Nublert** [rage/mooc.fi#517]
The Reporting Bot stuck:
Number of registered students doesn't update (no. of completed does)

**Comment by Nublert** [comment]
It's back - been stuck for 2 days

**Comment by mipyykko** [comment]
> It's back - been stuck for 2 days

Is it? Says it's run today (literally one minute before you posted), yesterday and the day before that.

**Comment by Nublert** [comment]
At least the numbers of registered haven't changed on Slack. If the automation as it is now sucks, now might be a good time to rethink it. We'll need a chart instead of a list when the number of versions grows.
