### ISSUE TITLE
tmc-cli-rust edited installation instructions for macOS, Linux & Windows

### ISSUE THREAD

**Issue by HoolaBoola** [rage/mooc.fi#728]
I have improved the (English) instructions for installing the client.

I am unable to commit and make a pull request, because pre-commit hooks won't pass (even though I've confirmed I haven't touched anything related to that kind of stuff). Nothing I did seemed to help, there was just these lines at the end:

```
Found 1283 errors.

Backend typecheck not successful.
husky - pre-commit hook exited with code 2 (error)
```

Instead, I have created a patch

[0001-Improved-tmc-cli-rust-installation-instructions-adde.patch.txt](https://github.com/rage/mooc.fi/files/6455125/0001-Improved-tmc-cli-rust-installation-instructions-adde.patch.txt)

Applying this patch should edit 3 files:

`frontend/static/md_pages/tmc-cli_installation_[Linux/Windows]_en.mdx`
`frontend/pages/[lng]/installation/tmc-cli.tsx`

Also the file `frontend/static/md_pages/tmc-cli_installation_macOS_en.mdx` should be created.

**Comment by mipyykko** [comment]
Create a PR, it's easier for me to apply.

**Comment by HoolaBoola** [comment]
Will do, hopefully this evening
